MODEL:
  NUM_CLASSES: 9 #NUM_CLASSES: 21 **modify-ganyongdong-2020.10.5
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2012_train", ) # TRAIN: ("voc_2007_trainval", "voc_2012_trainval") **modify-ganyongdong-2020.10.5
  TEST: ("voc_2012_test", )
SOLVER:
  MAX_ITER: 400000
  LR_STEPS: [10000, 20000, 60000, 100000, 150000, 220000]
  GAMMA: 0.7
  BATCH_SIZE: 18
  LR: 5e-4

OUTPUT_DIR: 'outputs/vgg_ssd300_voc0712'
